server:
  port: 18004

spring:
  datasource:
    url: jdbc:mysql://101.132.37.220:3306/user-center-dev?useUnicode=true&&characterEncoding=utf8&serverTimezone=GMT%2b8&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: '{cipher}d5ff70b24a3b0246ddb60072d9951f2e31febbde409b8fbffba66ecd1c0da8cb'
    password: '{cipher}c204164c9c8d60878982acbe2d6a429c02ea01285d76041e52fc6021c57e0e63'
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Druid数据源配置
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
