server:
  port: 18005

spring:
  datasource:
    url: jdbc:mysql://101.132.37.220:3306/user-center-dev?useUnicode=true&&characterEncoding=utf8&serverTimezone=GMT%2b8&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: '{cipher}AgAKkW0eUTxc4jFxRjk4zn567DCduFm+FBUoRIeIkCG1cTMu5KhigE5LOE5x2M+RNfHE/Ga9wQSHYIiNcr8VI3u+09MewFtCL5wPvTPKtycuaEHUOyMhF6zTBiwz/RtFqrabWZ3Qb+LBmv3CrAnz1TVOlqX6PnfB8tyffhfZiNctdl53A2sZff178BIXICgGuxVEmx3bLv9mjCiaGcgBXcInNfjU8lnDrVscj/3gRxyc6dAOt6dEewYA8mELydmyOQwevJ1jykhawgXP9FZ+mPfM4A0samIMPORUUAbS/OMVZntNCz9doxFF1QW1GiGkS0gaCrV6ae7mCgsS97pjRYJHeg258rXOduPylRFsvDuw4YKp535ksbUduNh9NtP6iJ0DyjbjyQxYoJza8C4TzJNpp8Bt/WPA8l7kt5v/kPgC/JMcJ5BhnTE7mPsKi8YlYrSIwNe+aCxMISBsARvZ40bOqIq+iKGKaLeEB/JoQvJ1V0603JcXjg0eBBXJjKNeAU7A6ZwilGB+TERJ1qNoSWVKBF17HgaHG+vUewN7x66ZwCH7RCnjcTfT0V+umR9V648t3hoGWH8AdHVfcIVYm0MIp9SZMKJKtZFOBQTkmsmdcaRXk4pQSlI3+SK+WhmZkttJvbrDc/+sHMVhlU0O6H0YdHtNN3+gVasYIrCiyI+7SpQXWm5Lqfi1oPFWhHJec5KL1pCmseK+nJsmJjlZznXA'
    password: '{cipher}AgBkkGaxRRPgwvxY3wlj775jddPmki6TVBI1OCEv0VMqD2MTJjSChLdWu1RO5gFO8c7NECKKxLj0/NcHizggTiMjZ8xnY+Ak3Q95kEu0yaupQKqInNoPRebOcmHSoK3ikX391GzEWLiOWdfezIwajYEp3nECpVh81d/JLCaAEb8k4BnVQYKBOIv8x7i7Y4cBOL3juOONIMfUi43CIVBnACWdSb79+KJhS7wCCNV0H0+elNdRpNaeEz90ey++WhzPQvOENkbzVnfYNtL/Am4ThW3cCETdwawqOcJTTFHwFu2Q9VZ5oF4zLR6JdFYO4rM4vg8A90lNrggCaCFX4waXZetytIoTTJy+obta0rozBAPXE0A22aFJTTGrYTevsLWnCmVuzvGI+n1zeyLcimKi8FTLZt5pqaF+0spO8ekXyDC9UW5pFAnbS+hiDILGtBqZzdKEUiCdmurNnegoEapbQg6hjrF0/BHy1tCo8w/iUnQHj2hOsOeJ1j1YBcyk+gT5YWpKxlJ4dEq4eM2uRGOaYkFBwDG3rGnR4HpdI6BVmP65lpfvj9oMNLSSBH3Lys1NeNHf+A4z+H6uQA6vD3lijw+YqOpcof5niTP1AWujdvopM69aap9jaCZomX4SZ2jKVMnXRRcjUqoaUauF1GssMcWFANFUnWpdIH9FhMGngPRq7IgLpOeKYm9PuuXtrknv7mcvn0OEUn+G8KImk9fyxG3N'
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Druid数据源配置
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
