server:
  port: 18004

spring:
  datasource:
    url: jdbc:mysql://101.132.37.220:3306/user-center-dev?useUnicode=true&&characterEncoding=utf8&serverTimezone=GMT%2b8&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: '{cipher}AgCDvx2oUCRXD+8EL0SndmgATbRhVaJjmzQuSklxCeXitm3AGuyGw31tV2blsB62dNYg7Gr+mpnx6PxAsqRdmxDVwpbHOyOAEcWbTbmlr53pQ62PJ3ZkqUGBtDfHHJGlyNb5ao7D3T8DuElIk0gfwBLYIi+chPx200DLqQ/1fM4WC2HPs4YdGhm1/vFozT3ailVI4tPcaXRfblhMh0x0u6sX0V1V+LJJHaZ9FLUWmLmThuir55i1c/6B00bb0JZDuLb+GrKc0TIJ0mn2ciTPcdmnlUU82fHQib0EOXy+LiYRDLnxcogiA1o7rmkDNmOXHg+ov6HcOnEKDEssnlKwYgtm3Gm7FDfQFqZH3O/Cs3nNFr970GLnCAe5VVsw8roGzcDpAjbXBVk9G8T3pmGbyK5Z/dCUqC19sUr9Iw8Bozk/UJJ7fwMKRb3MXqppvBmGLeKLhYzahMxKdedcObJL31qQrB2V+1DEeRbkSee4/MfF+y15dBXiW3+8GvffiUuc25kh3mtzntXCDsCF65UeIg+YF1zH0fexVkLqOTr3gcll60fwELv7yGzDluZK3jWmhnGsSKYkk/r7w8MDaCS0F0b0TlhwQco7bREQgtZ2yT3ud9CC8qrcTyABMY6K3k2wIKjrEw82QHP9NQOIYdxJ50C3qT6RW77QqS7wTyam6es/sKySqIJYeOqRMGpfzi/7ljMWxOaJIoz++8+p3gxNAuJi'
    password: '{cipher}AgAMBINpNP8AArAfppGB0Q2sO0c2lnCVNSvxqadu6HaxVAeokBok1loALp2A7+C74Snxa2jXEzpXOiJAAEGZDSndcJObgU02bB579LTshmzJaMUYZ44yTTMQ4dUPCiX9NIQyD33AE0LarIm6QmjW1BW/w/tnXQSwVAVY+WMX19QjNj/Cggxl9MqukxebDWVmo+E5yqpX8HlgR0KWBnQXJsKkRuP6njxD/ee1DSAEnd3jHXE/5k6Qvp8tbASszrzPqyGf1De1kHaElLfA+apSSqyOUocHP4FQn1gIfZRkQqwn7GA2CUS3q64OKAt7Uvx1tkRqCezFoT6/OBXU2k9HWC2ZJU6RSHvy37QsYHcFg29w6N5YWr87iLWgOSD6aND/TexM+WjIBhLSn8xsxG8zmp3pA0NPzZWcZTFSZs0l3KhgIBV5Kg5d93jM3X3ridDBePuDpUuIk50pWoJ8RRZGjlVl2YHC2EXx0Imh1ve2Y1mC0d4LTllD42CvxLxudhesDiP99NXcyfj4ootgMOCk+vnVCczY3NkoQ98WfEPCJq6BwZEppQ4Ektd23rJFBtgkACxMXCOLNtzVZSNHt1kZyMxICgdSt1L5iV2UfpdUcYq/tDOwpGzozYHsQltAIJTGNlnwkiqW6Jx7IkIG2FZSI3Ocm/a3FoezyJhVxKD3AJ0FcqGbJkwrh37jn7r3A8DJblt/8T1/lWw351+Ml1f0URqP'
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Druid数据源配置
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
