server:
  port: 18003

spring:
  datasource:
    url: jdbc:mysql://101.132.37.220:3306/auth-dev?useUnicode=true&&characterEncoding=utf8&serverTimezone=GMT%2b8&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: '{cipher}AgBATbXIspJ13US5934cdTJW55JpkEzJnJ/S+/XFuYpwjDKFmkdzDAJPteipia34dpXKiAwvIYD8BeFaZz4Vhg69YZjB8rviEaCcpxKtL7eYbzLyLq1YxE5uV+3bIgSifOshAuSJ57O9U1p0cpfichomDzQ0L9FLXYe37k8Vc+IUXqgJ1qLKMNbi5650LB8ekDOc66adszfsorjYSjRV8TSr2h4prqcTLUqMcLxkEUFMRzy3FL7imGmvLtc0TAYw9x6L7mMfPOiDI/VBVYKPg53r+94Gy+lHbWBGa1DWDS9SnQQbHE8ZSmY1RIys/4x1gklBxsFWQ//Zyo88ZQrIr+M0ErZ51ks+JboUGdZHhQTRpMI3vaEYqpVwTpF2KxErFlmP4haVef9+ty4zPxZaJoPK0l11y0djqhvLF0Y6ons4/MW2gsPrdXRDcngExAQh1psygfNp6bXgVistJiWD0a/jEiCsusvgFLH6bluAboQfhD18zDLejRk+4WShpg2/HSnYCz4k+r6+r4cQxh1aLiRNKe8FHXDNc8stkx7vm59S6ESUVvjIr7SJBlfWtq/eWUFtNIvcTL9pf1SzWHaBaYAZ9pfyxKgN9F7SHGp9bBHhhENMxl68E9kwdsoSQdRcl9oDAGXYiam2wgEmFEhiToB3oAfZmZGFHRLce21pc1dpSfJGJJN5FRefMxVbnm0VAaOM494Lw21qk/NkHJKsODTg'
    password: '{cipher}AgBgePn7axSjkFaxxq2wD7heM0vsK2B+jsIKbyrtiVmLWtcV0VH7+67du/dCAXxMaMNYuu1MjJFa3zaE+frWPNCN8fz5L6hWYQa4sFfN3q4AIa4Wgiq7VdY78iRKkyPTUvlOuQtwSDMh8o+osCN1HtiwhhR2v6rkTfz46lRbg4BQS5g1NAZ7cvDgOD0NBgvPNCuy2IHK43X9NqIuWXGp7YjXNDAuHWJpifsZGeKX7VYmv3E7EZbZt7Rz2Eq96HVgHv+BcRv+ZhmbgG0GaMarhBzOy8+1yFxmxPuXdCvsrrER3dS5eESef/Tdn+KRwWPR/L/+XQy3L5M9/gYdX6AFxQibKxdgvF41gVgDY5CV8PlvOpskORg5ds6c8jToHMiotz6AZdYYiElvx4wcPeVU1SwiYr203s4HojXpalOo9r95iIkq3UyIqNKWkEMFf1oOytCyJ+gKIYM6trj+oj9mf1oEixBLvFebjvHZcEtiMYuTslA8iWyu04cFyZ9QF28VwVzp5v+pFeOS1oFnMzizKFyPU+bv9wfQUqb0iw9jVpnSBNoooQsJpAH4iKuFs43hhdw1oSDunMHd/y5lzmSo5F6xhEjJXB6KkxPkmNKk/5ZIgbcDY4gmVWa7PeoQaKRqN0OpG5IQEqdY7cATkRva+ES6GREVXPzYTohjbrAsBHYcF/usTWckMjnoWystPRo3I2MZHL8ZkgRaCFXU32UcceEH'
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Druid数据源配置
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

jrmarcco:
  jwt:
    expire: 30