spring:
  redis:
    host: 101.132.37.220
    port: 6379
    password: '{cipher}AgBxBYzhJo6qZaW/c663ODTPVIYRdyCTrgpFIWssSmrgZ8zNWP9yAUbZbIE6V0rTgsHIh0SXWH8x9kGARv1Ah6r8CSCbqyBBvBVMFbMbzB917R7mVF3ddNiMBIKIWCyY3blI0rcL6qjmYBsecjhe0+zZw69tOHhE+PB713FWyDnjA8L9KSX9lUVCMw412Jt5mRj7rBaD7A0npGb2Yxv1Yfjr3xXp0dj4YFDHt0oNxJ18z7aRejHSMs2vNJGxC/oaDpRdX6+AqirmOS3rQtUaic5/lw4ylWdeMab2soK/JRVZdq670juIVBxdHADBziqNDDtIJYij7xNmYrsVCvsFtcNbld/IgSDLLJTEzP+vH0ieclqkGGpd94Ab77TgES5J1oAOb04Z6TBP8x92K2DIgD78j9iygTkFnjJUbaHO0vJOyiKhznRgohN77y1kYyXjGNl2CH+5IRUpNGohC0m0ojBzKEi92XWE3e098/gaMyQ72dqu7IWmgA55ek6WcuXjweEYm8BHWOipiFvO15TzjfEj5EaKXymY0fw+5V938dtPbYuRHPGlI6fS3GOYxDdhtkPNDNuR8IRPkSNfEf8yqVAESd2Jx+5kqfnSRQmUFh37eI2Q9FojPshPZdNm4A7lKuADYFJ6oRQSKgHbMMz5w98MTALzk/9oirLINpZlarnRSaB9zsjE9Qu5kPTZDjHYX/uyZkwbNUtehijBtRn9hEjc'
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: -1ms