spring:
  redis:
    host: 101.132.37.220
    port: 6379
    password: '{cipher}21cb331b522ccaa13e441c396a3061cb9fc6727e320ebfc5d1f9ff4468390682'
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: -1ms