spring:
  redis:
    host: 101.132.37.220
    port: 6379
    password: '{cipher}AgAmm5XTuMteWryyrGGGRvqn3ZW9XXPAJnmQUrUh5HEGy45EHT+pIXrqFLyWn8RFFJpuw3hbuR15ZTy80O+xuWMZj5BqniTdbM2eBaPOZxPGXWrDOOMlR8ZifooP6z1W1HhVscPy9ttsMxlOiau8hiGkdIWxDsUeYgnO8XjyGCeikSpfj2wBz27APgJ1436liq+ozK/lM5IAk2lNGk0WICWoWtvYoy04n/hI+kC15X43VC/JWZ1WhBMsAyNr6ha91LyuMtGXZEwL/90TQfEhwxj0UDkNOWawPR/X1sVOnZOhFg+rJ/TpUJiPCuiTXUfzOMsakmUYV9O8QrZQbXo2XxZMb+FYTOhH74Zvx8TwzalsKWZ1/J6P80m1gqkGf2I/8v2/qaI8W8KedreL65Rp1WiO8sKlEHzKoXgy1nXFd+FSD2P2Jfjux3VBTFEy3KMvG/Xibf6SqfmQTt9b/VmBGtAelJkcz5z2kc1/nzlazX7GG1JuKfVtuE0M9k2VzlD4KwIIBFoVbIOAhttVCxPoj3HAL15Ry7YZ5PpsqB/NjUVjl/sAJgkZgGObSKYLeL/kqCHhJjqmxSdbLEyh/zkViQwYhrxfII/KFnq60RfNG8unfx9nHUeQ6sR399kB5/eaKnnE4sJkWedPx3ZvnEx91WWcFIpJLzgbdGNJ5Fkq9swSZRdQgIfK37QmA1Spn4QLaYh6Xb884FcODcoiAg+Io4m7'
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: -1ms